import type { Metadata } from "next"
import { Playfair_Display, Manrope } from "next/font/google"
import "./globals.css"
import { JsonLd } from "./componants/JsonLd"

const playfairDisplay = Playfair_Display({
     variable: "--font-playfair_display",
     subsets: ["latin"],
     style: ["normal", "italic"],
     weight: ["400", "500", "600", "700", "800", "900"],
})

const manrope = Manrope({
     variable: "--font-manrope",
     subsets: ["latin"],
})

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
     return (
          <html lang="fr" className={`${playfairDisplay.variable} ${manrope.variable} font-man h-full antialiased`}>
               <body className="bg-bg">
                    <JsonLd />
                    {children}
               </body>
          </html>
     )
}
